version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    volumes:
      - ../backend:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: blog
      DB_USERNAME: bloguser
      DB_PASSWORD: secret
      APP_ENV: local
      APP_DEBUG: 'true'
    depends_on:
      - db

  web:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ../backend:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db-data:
